stages:
  - basic-platform
  - other-platforms

.runner:
  only:
    - merge_requests
  tags:
    - development
  variables:
    GIT_SUBMODULE_STRATEGY: "normal"
    IMAGE_REGISTRY: "code.usgs.gov:5001/ghsc/gmp/earth-structure/cvms/geomodelgrids"

.builder:
  extends:
    - .runner
  stage: other-platforms
  variables:
    ENABLE_GDAL: "yes"
    ENABLE_VALGRIND: "no"
  script:
    - docker/testenv-build.sh
    - ci-config/run_tests.sh

.builder-first:
  extends: .builder
  stage: basic-platform

.doc:
  extends: .runner
  image: $IMAGE_REGISTRY/testenv-debian-stable
  script:
    - echo "-TODO- Generate documentation."

ubuntu-20.04:
  extends: .builder-first
  image: $IMAGE_REGISTRY/testenv-ubuntu-20.04

ubuntu-22.04:
  extends: .builder
  image: $IMAGE_REGISTRY/testenv-ubuntu-22.04

ubuntu-23.04:
  extends: .builder
  image: $IMAGE_REGISTRY/testenv-ubuntu-23.04

ubuntu-23.10:
  extends: .builder
  image: $IMAGE_REGISTRY/testenv-ubuntu-23.10

deb-stable-valgrind:
  extends: .builder
  image: $IMAGE_REGISTRY/testenv-debian-stable
  variables:
    ENABLE_VALGRIND: "yes"

deb-testing-coverage:
  extends: .builder
  image: $IMAGE_REGISTRY/testenv-debian-testing
  variables:
    TEST_COVERAGE: "yes"
    PYTHON_COVERAGE: "coverage3"

fedora-38:
  extends: .builder
  image: $IMAGE_REGISTRY/testenv-fedora-38

fedora-39:
  extends: .builder
  image: $IMAGE_REGISTRY/testenv-fedora-39
rockylinux-8:
  extends: .builder
  image: $IMAGE_REGISTRY/testenv-rockylinux-8
  variables:
    ENABLE_GDAL: "no"

rockylinux-9:
  extends: .builder
  image: $IMAGE_REGISTRY/testenv-rockylinux-9
  variables:
    ENABLE_GDAL: "no"

documentation:
  stage: basic-platform
  extends: .doc
