remote_theme: pmarsceill/just-the-docs
title: GeoModelGrids
baseurl: /geomodelgrids
aux_links:
    "GitHub repository":
      - "//github.com/baagaard-usgs/geomodelgrids"

color_scheme: usgs
heading_anchors: false
search_enabled: true

title_image: images/USGSsimple.png
software_version: 0.1.0
