remote_theme: pmarsceill/just-the-docs
title: GeoModelGrids
baseurl: /geomodelgrids
#search_enabled: true
aux_links:
    "GitHub repository":
      - "//github.com/baagaard-usgs/geomodelgrids"

color_scheme: usgs
heading_anchors: false
search_enabled: true

geomodelgrids-version: 0.1.0
