remote_theme: baagaard-usgs/just-the-docs
title: GeoModelGrids
baseurl: /geomodelgrids
aux_links:
  "GitHub repository":
    - "//github.com/baagaard-usgs/geomodelgrids"

color_scheme: usgs_lightbg
heading_anchors: false
search_enabled: true

title_image: images/USGSsimple.png
software_version: 1.0.0rc1
